### ISSUE TITLE
custom my own SCHEDULER_QUEUE_CLASS failed

### ISSUE THREAD

**Issue by light8lee** [rmax/scrapy-redis#114]
I write a random access queue for scheduler, but it doesnt work.
my code is 
``` python
from scrapy_redis.queue import Base

class RandomQueue(Base):
    """ Random access the value (with blocking)"""

    def __len__(self):
        """Return the length of the stack"""
        return self.server.smembers(self.key)

    def push(self, request):
        """Push a request"""
        self.server.sadd(self.key, self._encode_request(request))

    def pop(self, timeout=0):
        """Pop a request"""
        data = None
        while data is None:
            data = self.server.spop(self.key)

        return self._decode_request(data)
```

and in settings.py, I set `SCHEDULER_QUEUE_CLASS = "randque.randque.RandomQueue"`, when I run my spider, I got this info:

``` shell
:0: UserWarning: You do not have a working installation of the service_identity module: 'cannot import name opentype'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
2017-12-26 16:02:00 [scrapy.utils.log] INFO: Scrapy 1.4.0 started (bot: scrapybot)
2017-12-26 16:02:00 [scrapy.utils.log] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'recursive_crawler.spiders', 'DUPEFILTER_CLASS': 'filter.dupefilter.SqlDupeFilter', 'SPIDER_LOADER_WARN_ONLY': True, 'SPIDER_MODULES': ['recursive_crawler.spiders'], 'USER_AGENT': 'scrapy-redis (+https://github.com/rolando/scrapy-redis)', 'SCHEDULER': 'scrapy_redis.scheduler.Scheduler', 'DOWNLOAD_DELAY': 1}
2017-12-26 16:02:00 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2017-12-26 16:02:00 [RecursiveSpider] INFO: Reading start URLs from redis key 'to_crawl' (batch size: 16, encoding: utf-8
2017-12-26 16:02:00 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2017-12-26 16:02:00 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2017-12-26 16:02:00 [scrapy.middleware] INFO: Enabled item pipelines:
['recursive_crawler.pipelines.RecursiveCrawlerPipeline']
2017-12-26 16:02:00 [scrapy.core.engine] INFO: Spider opened
2017-12-26 16:02:00 [scrapy.core.engine] INFO: Closing spider (shutdown)
2017-12-26 16:02:00 [scrapy.core.engine] ERROR: Scraper close failure
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/engine.py", line 311, in <lambda>
    dfd.addBoth(lambda _: self.scraper.close_spider(spider))
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/scraper.py", line 86, in close_spider
    slot.closing = defer.Deferred()
AttributeError: 'NoneType' object has no attribute 'closing'
2017-12-26 16:02:00 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'finish_reason': 'shutdown',
 'finish_time': datetime.datetime(2017, 12, 26, 8, 2, 0, 148957),
 'log_count/ERROR': 1,
 'log_count/INFO': 7}
2017-12-26 16:02:00 [scrapy.core.engine] INFO: Spider closed (shutdown)
Unhandled error in Deferred:
2017-12-26 16:02:00 [twisted] CRITICAL: Unhandled error in Deferred:

2017-12-26 16:02:00 [twisted] CRITICAL:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 95, in crawl
    six.reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/crawler.py", line 79, in crawl
    yield self.engine.open_spider(self.spider, start_requests)
TypeError: an integer is required
```

where do I go wrong?

**Comment by rmax** [comment]
Hi, `__len__` must return an intenger. You should use `scard` instead of `smembers` command.
