### ISSUE TITLE
Something wrong in scheduler

### ISSUE THREAD

**Issue by taozi926494** [rmax/scrapy-redis#135]
Hello rmax:
I start a same name crawler in different project, then a  CRITICAL: Unhandled Error happend. the project_1 scheduled project_2's spider.  I think there is something wrong in scheduler

Here my project_1 code:

settings.py
CONCURRENT_REQUESTS = 2
SCHEDULER = "scrapy_redis.scheduler.Scheduler"
DUPEFILTER_CLASS = "scrapy_redis.dupefilter.RFPDupeFilter"
REDIS_URL = 'redis://localhost:6379'

spiders > redis.py
class RedisSpider(RedisSpider):
    name = 'redis'
    redis_key = 'pj1_redis:start_urls'

    def make_request_from_data(self, data):
        url = bytes_to_str(data, self.redis_encoding)
        return scrapy.Request(url=url, callback=self.parse_one)

    def parse_one(self, response):
        logging.debug('-- from data return --- 1111111111')

project_2 code:

settings.py
CONCURRENT_REQUESTS = 2
SCHEDULER = "scrapy_redis.scheduler.Scheduler"
DUPEFILTER_CLASS = "scrapy_redis.dupefilter.RFPDupeFilter"
REDIS_URL = 'redis://localhost:6379'

spiders > redis.py
class RedisSpider(RedisSpider):
    name = 'redis'
    redis_key = 'pj2_redis:start_urls'

    def make_request_from_data(self, data):
        url = bytes_to_str(data, self.redis_encoding)
        return scrapy.Request(url=url, callback=self.parse_two)

    def parse_two(self, response):
        logging.debug('-- from data return --- 2222222222')

----------- Redis url push file -----------
urlpush.py

import redis
def num_to_str(num):
    return str(num) if num > 9 else '0' + str(num)

url = 'http://www.umetrip.com/mskyweb/fs/fa.do?dep=KWE&arr=PEK&date=2018-'
rediscli = redis.Redis(host='localhost', port=6379)
for month in range(1, 11):
    for day in range(1, 28):
        tmp_url = url + num_to_str(month) + '-' + num_to_str(day)
        rediscli.lpush('pj1_redis:start_urls', tmp_url)
        rediscli.lpush('pj2_redis:start_urls', tmp_url)

----------- Here error logs -----------
project_1 log:

......
......
......
2018-11-05 21:32:18 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.umetrip.com/mskyweb/fs/fa.do?dep=KWE&arr=PEK&date=2018-10-08> (referer: None)
2018-11-05 21:32:18 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.umetrip.com/mskyweb/fs/fa.do?dep=KWE&arr=PEK&date=2018-10-09> (referer: None)
2018-11-05 21:32:18 [root] DEBUG: -- from data return --- 1111111111
2018-11-05 21:32:18 [root] DEBUG: -- from data return --- 1111111111
2018-11-05 21:32:18 [redis] DEBUG: Read 2 requests from 'pj1_redis:start_urls'
2018-11-05 21:32:18 [redis] DEBUG: Read 2 requests from 'pj1_redis:start_urls'
2018-11-05 21:32:18 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.umetrip.com/mskyweb/fs/fa.do?dep=KWE&arr=PEK&date=2018-10-04> (referer: None)
2018-11-05 21:32:19 [root] DEBUG: -- from data return --- 1111111111
2018-11-05 21:32:19 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.umetrip.com/mskyweb/fs/fa.do?dep=KWE&arr=PEK&date=2018-10-05> (referer: None)
2018-11-05 21:32:19 [root] DEBUG: -- from data return --- 1111111111
2018-11-05 21:32:19 [redis] DEBUG: Read 2 requests from 'pj1_redis:start_urls'
2018-11-05 21:32:19 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "d:\anaconda3\lib\site-packages\scrapy\commands\crawl.py", line 58, in run
    self.crawler_process.start()
  File "d:\anaconda3\lib\site-packages\scrapy\crawler.py", line 291, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "d:\anaconda3\lib\site-packages\twisted\internet\base.py", line 1261, in run
    self.mainLoop()
  File "d:\anaconda3\lib\site-packages\twisted\internet\base.py", line 1270, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "d:\anaconda3\lib\site-packages\twisted\internet\base.py", line 896, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "d:\anaconda3\lib\site-packages\scrapy\utils\reactor.py", line 41, in __call__
    return self._func(*self._a, **self._kw)
  File "d:\anaconda3\lib\site-packages\scrapy\core\engine.py", line 122, in _next_request
    if not self._next_request_from_scheduler(spider):
  File "d:\anaconda3\lib\site-packages\scrapy\core\engine.py", line 149, in _next_request_from_scheduler
    request = slot.scheduler.next_request()
  File "d:\anaconda3\lib\site-packages\scrapy_redis\scheduler.py", line 172, in next_request
    request = self.queue.pop(block_pop_timeout)
  File "d:\anaconda3\lib\site-packages\scrapy_redis\queue.py", line 117, in pop
    return self._decode_request(results[0])
  File "d:\anaconda3\lib\site-packages\scrapy_redis\queue.py", line 48, in _decode_request
    return request_from_dict(obj, self.spider)
  File "d:\anaconda3\lib\site-packages\scrapy\utils\reqser.py", line 50, in request_from_dict
    cb = _get_method(spider, cb)
  File "d:\anaconda3\lib\site-packages\scrapy\utils\reqser.py", line 87, in _get_method
    raise ValueError("Method %r not found in: %s" % (name, obj))
builtins.ValueError: Method 'parse_two' not found in: <RedisSpider 'redis' at 0x52a2ba8>

2018-11-05 21:32:23 [redis] DEBUG: Read 2 requests from 'pj1_redis:start_urls'
2018-11-05 21:32:23 [redis] DEBUG: Read 2 requests from 'pj1_redis:start_urls
......
......
......

project_2 log:
......
......
......
2018-11-05 21:32:54 [root] DEBUG: -- from data return --- 2222222222
2018-11-05 21:32:54 [root] DEBUG: -- from data return --- 2222222222
2018-11-05 21:32:54 [redis] DEBUG: Read 2 requests from 'pj2_redis:start_urls'
2018-11-05 21:32:54 [redis] DEBUG: Read 2 requests from 'pj2_redis:start_urls'
2018-11-05 21:32:55 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.umetrip.com/mskyweb/fs/fa.do?dep=KWE&arr=PEK&date=2018-04-19> (referer: None)
2018-11-05 21:32:55 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.umetrip.com/mskyweb/fs/fa.do?dep=KWE&arr=PEK&date=2018-04-18> (referer: None)
2018-11-05 21:32:55 [root] DEBUG: -- from data return --- 2222222222
2018-11-05 21:32:55 [root] DEBUG: -- from data return --- 2222222222
2018-11-05 21:32:55 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "d:\anaconda3\lib\site-packages\scrapy\commands\crawl.py", line 58, in run
    self.crawler_process.start()
  File "d:\anaconda3\lib\site-packages\scrapy\crawler.py", line 291, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "d:\anaconda3\lib\site-packages\twisted\internet\base.py", line 1261, in run
    self.mainLoop()
  File "d:\anaconda3\lib\site-packages\twisted\internet\base.py", line 1270, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "d:\anaconda3\lib\site-packages\twisted\internet\base.py", line 896, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "d:\anaconda3\lib\site-packages\scrapy\utils\reactor.py", line 41, in __call__
    return self._func(*self._a, **self._kw)
  File "d:\anaconda3\lib\site-packages\scrapy\core\engine.py", line 122, in _next_request
    if not self._next_request_from_scheduler(spider):
  File "d:\anaconda3\lib\site-packages\scrapy\core\engine.py", line 149, in _next_request_from_scheduler
    request = slot.scheduler.next_request()
  File "d:\anaconda3\lib\site-packages\scrapy_redis\scheduler.py", line 172, in next_request
    request = self.queue.pop(block_pop_timeout)
  File "d:\anaconda3\lib\site-packages\scrapy_redis\queue.py", line 117, in pop
    return self._decode_request(results[0])
  File "d:\anaconda3\lib\site-packages\scrapy_redis\queue.py", line 48, in _decode_request
    return request_from_dict(obj, self.spider)
  File "d:\anaconda3\lib\site-packages\scrapy\utils\reqser.py", line 50, in request_from_dict
    cb = _get_method(spider, cb)
  File "d:\anaconda3\lib\site-packages\scrapy\utils\reqser.py", line 87, in _get_method
    raise ValueError("Method %r not found in: %s" % (name, obj))
builtins.ValueError: Method 'parse_one' not found in: <RedisSpider 'redis' at 0x52a2c18>

2018-11-05 21:32:55 [redis] DEBUG: Read 2 requests from 'pj2_redis:start_urls'
2018-11-05 21:32:55 [redis] DEBUG: Read 2 requests from 'pj2_redis:start_urls'
2018-11-05 21:32:55 [scrapy.core.engine] DEBUG: Crawled (200) <GET http://www.umetrip.com/mskyweb/fs/fa.do?dep=KWE&arr=PEK&date=2018-04-14> (referer: None)
.......
.......
.......

Can you finger out the reason that my error happen, please. Thank you very much !!

**Comment by rmax** [comment]
Why do you use different projects with the same spider name sharing same redis instance? That could cause the problem.

The code assumes the callback is available in the spider instance.

**Comment by rmax** [comment]
Yes. This project's defaults assumes the redis instance is dedicated to the project. That's why keys collides and you get requests in a spider that doesn't support the given callback.

**Comment by taozi926494** [comment]
ya I see, Thanks !
