### ISSUE TITLE
TypeError: can't pickle Selector objects

### ISSUE THREAD

**Issue by twenty-3rd** [rmax/scrapy-redis#138]
Hello， I want to change my crawlspider to rediscrawlspider，and then the bug appear：
2019-01-09 10:28:54 [twisted] CRITICAL: Unhandled error in Deferred:
2019-01-09 10:28:54 [twisted] CRITICAL:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\twisted\internet\task.py", line 517, in _oneWorkUnit
    result = next(self._iterator)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\utils\defer.py", line 63, in <genexpr>
    work = (callable(elem, *args, **named) for elem in iterable)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\core\scraper.py", line 183, in _process_spidermw_output
    self.crawler.engine.crawl(request=output, spider=spider)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\core\engine.py", line 210, in crawl
    self.schedule(request, spider)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\core\engine.py", line 216, in schedule
    if not self.slot.scheduler.enqueue_request(request):
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy_redis\scheduler.py", line 167, in enqueue_request
    self.queue.push(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy_redis\queue.py", line 99, in push
    data = self._encode_request(request)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy_redis\queue.py", line 43, in _encode_request
    return self.serializer.dumps(obj)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy_redis\picklecompat.py", line 14, in dumps
    return pickle.dumps(obj, protocol=-1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\parsel\selector.py", line 204, in __getstate__
    raise TypeError("can't pickle Selector objects")
TypeError: can't pickle Selector objects

I know the bug mean but I just want to use rediscrawlspider to dupefilter, why the selector appear?
Additional, if I del the callback of rule, it work fine but make no sence:
Rule(LinkExtractor(restrict_xpaths='//li[@class="pj-box-li"]', allow=r'/project/.+'), callback='parse_detail')

the pip list:
lxml                               4.1.0
parsel                             1.5.0
pywin32                            221
redis                              2.10.6
requests                           2.18.4
Scrapy                             1.5.1
scrapy-redis                       0.6.8
scrapyd                            1.2.0
testpath                           0.3.1
Twisted                            17.9.0
urllib3                            1.22
python  3.6.7
Thanks!

**Comment by twenty-3rd** [comment]
here is the settings.py:
DUPEFILTER_CLASS = "scrapy_redis.dupefilter.RFPDupeFilter"
SCHEDULER = "scrapy_redis.scheduler.Scheduler"
SCHEDULER_PERSIST = True
REDIS_URL = "redis://127.0.0.1:6379/"

  "settings": {
    "LOG_LEVEL": "DEBUG",
    "RETRY_ENABLED": true,
    "RETRY_TIMES": 3,
    "AUTOTHROTTLE_ENABLED": true
  },

**Comment by twenty-3rd** [comment]
the spider code:
class NewLoader(ItemLoader):
    default_output_processor = TakeFirst()


class MakuakeLoader(NewLoader):
    text_out = Compose(Join(), lambda s: s.strip())
    source_out = Compose(Join(), lambda s: s.strip())


class MakuakeSpider(RedisCrawlSpider):
    name = 'makuake'
    redis_key = 'makuake'

    def __init__(self, name, *args, **kwargs):
        config = get_config(name)
        self.config = config
        self.rules = rules.get(config.get('rules'))
        # self.start_urls = config.get('start_urls')
        self.allowed_domains = config.get('allowed_domains')
        super(MakuakeSpider, self).__init__(*args, **kwargs)

    def parse_detail(self, response):
        item = self.config.get('item')
        if item:
            cls = eval(item.get('class'))()
            loader = eval(item.get('loader'))(cls, response=response)

            for key, value in item.get('attrs_1').items():
                for extractor in value:
                    if extractor.get('method') == 'xpath':
                        loader.add_xpath(key, *extractor.get('args'), **{'re': extractor.get('re')})
                    if extractor.get('method') == 'css':
                        loader.add_css(key, *extractor.get('args'), **{'re': extractor.get('re')})
                    if extractor.get('method') == 'value':
                        loader.add_value(key, *extractor.get('args'), **{'re': extractor.get('re')})
                    if extractor.get('method') == 'attr':
                        loader.add_value(key, getattr(response, *extractor.get('args')))
                    if extractor.get('method') == 'eval':
                        loader.add_value(key, eval(extractor.get('args')[0]), **{'re': extractor.get('re')})

**Comment by twenty-3rd** [comment]
the problem is I try to pick loader，I remove it and work fine！
