### ISSUE TITLE
scrapy_redis/picklecompat builtins.ValueError: unsupported pickle protocol: 5

### ISSUE THREAD

**Issue by StudyExchange** [rmax/scrapy-redis#170]
**ENV:**
python: Python 3.7.4
scrapy-redis: 0.6.8

**Error info:**
2020-06-04 09:42:45 [twisted] CRITICAL: Unhandled Error
Traceback (most recent call last):
  File "run_static_webpage_spider.py", line 18, in <module>
    process.start()
  File "/root/anaconda3/lib/python3.6/site-packages/scrapy/crawler.py", line 309, in start
    reactor.run(installSignalHandlers=False)  # blocking call
  File "/root/anaconda3/lib/python3.6/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/root/anaconda3/lib/python3.6/site-packages/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/root/anaconda3/lib/python3.6/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/root/anaconda3/lib/python3.6/site-packages/scrapy/utils/reactor.py", line 41, in __call__
    return self._func(*self._a, **self._kw)
  File "/root/anaconda3/lib/python3.6/site-packages/scrapy/core/engine.py", line 122, in _next_request
    if not self._next_request_from_scheduler(spider):
  File "/root/anaconda3/lib/python3.6/site-packages/scrapy/core/engine.py", line 149, in _next_request_from_scheduler
    request = slot.scheduler.next_request()
  File "/root/anaconda3/lib/python3.6/site-packages/scrapy_redis/scheduler.py", line 172, in next_request
    request = self.queue.pop(block_pop_timeout)
  File "/root/anaconda3/lib/python3.6/site-packages/scrapy_redis/queue.py", line 117, in pop
    return self._decode_request(results[0])
  File "/root/anaconda3/lib/python3.6/site-packages/scrapy_redis/queue.py", line 47, in _decode_request
    obj = self.serializer.loads(encoded_request)
  File "/root/anaconda3/lib/python3.6/site-packages/scrapy_redis/picklecompat.py", line 10, in loads
    return pickle.loads(s)
builtins.ValueError: unsupported pickle protocol: 5

**Comment by BobDu** [comment]
You ever used python 3.8 run this spider connection same redis server.
Please delete redis key `spider_name:requests` in your redis.

**Comment by zhangruinan** [comment]
obviously, start from python3.8, more pickle protocol was added, and by default, I suppose scrapy-redis uses the latest one. You may delete the old `spider:requests` or just upgrade to `python 3.8` or above ; the problem should be solved.

**Comment by LuckyPigeon** [comment]
Close this as a solved issue
